namespaces:
  - name: gitlab
    labels:
      istio-injection: enabled
  - name: dev-redis
    labels:
      istio-injection: enabled
  - name: gitlab-runner-sandbox
    labels:
      istio-injection: enabled
      zarf.dev/agent: ignore
  - name: gitlab-runner
    labels:
      istio-injection: enabled
  - name: sonarqube
    labels:
      istio-injection: enabled
  - name: metallb-system
    labels:
      istio-injection: disabled
  - name: confluence
    labels:
      istio-injection: enabled
  - name: jira
    labels:
      istio-injection: enabled
  - name: mattermost
    labels:
      istio-injection: enabled
  - name: nexus
    labels:
      istio-injection: enabled
  - name: keycloak
    labels:
      istio-injection: enabled
  - name: cert-manager
